config/routes.rb
Rails.application.routes.draw do

    namespace :mercury do
      resources :images
    end
  mount Mercury::Engine => '/'
  scope '(/:locale)' do
    resources :pictures
    resources :products do 
      member do
        get 'buy'
        post 'pay'
      end
    end

    resources :categories

    resources :payments do 
      member do
        post 'bancontact_koper'
        post 'bancontact_winnaar' 
        get 'bancontact_koper'
        get 'bancontact_winnaar' 
      end
    end

    resources :payment_notifications #used for paypal
    resources :payment_transactions  #used for paymill
  end

  root to: "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

  #TODO: this is now with strong params...
  #attr_accessible :description, :name, :price
  #attr_accessible :pictures_attributes, :category_id
  #has_many :product_pictures, :dependent=>:destroy
  #has_many :pictures, :through => :product_pictures #, :source=>''
  belongs_to :category
  has_many :pictures
  accepts_nested_attributes_for :pictures, :allow_destroy => true 
  # , :reject_if => proc {|attributes| attributes['filename'].blank? && attributes['filename_cache'].blank?}


#accepts_nested_attributes_for :photo, \
#  :reject_if => proc {|attributes| attributes['filename'].blank? \
#    && attributes['filename_cache'].blank?}



  def thumbnail
    if pictures.count>0
      pictures.order("created_at").last.pic.thumb
    else  
      #ActionController::Base.helpers.image_tag("missing.png")
      "/assets/missing.png"
    end
  end

  def first_picture
    if pictures.count>0
      pictures.first.try(:pic).try(:larger)
    else
      "/assets/missing.png"
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_login!, :except=>[:index, :show, :buy, :pay]
  skip_before_filter :authorize, :only=>[:index,:show, :buy, :pay] #no login or permission checks for downloading (it's with a md5 hash)


  #include ActionController::MimeResponds
  #include ActionController::RespondWith
 
  respond_to :html, :json, :js


  #paymill transaction here...
  def buy
    @product = Product.find( params[:id] )
  end

  def pay
    begin
      require "paymill"
      @product = Product.find( params[:id] )
 
      #use these keys
      #APP_CONFIG[:payment][:private_key]
      #APP_CONFIG[:payment][:public_key]
      Paymill.api_key = APP_CONFIG[:payment][:private_key]
      
      #Actual payment transaction from paymill here!
      transaction = Paymill::Transaction.create(  amount: (params[:amount].to_f*100).to_i,
                                    currency:    "EUR",
                                    description: "3D kit: #{@product.id}",
                                    token:       params[:paymillToken] )

      #example 
      #<Paymill::Transaction:0x007fbe2d63a4c8 @description="3D kits payment", @livemode=false, @invoices=[], @short_id=nil, @updated_at=2013-08-26 17:01:23 +0200, @status="closed", @origin_amount=69900, @client={"id"=>"client_e4fb7f288afc4912e864", "email"=>nil, "description"=>nil, "created_at"=>1377529283, "updated_at"=>1377529283, "app_id"=>nil, "payment"=>[], "subscription"=>nil}, @preauthorization=nil, @response_code=20000, @app_id=nil, @payment={"id"=>"pay_0da0e530efeaf532e5f2d87f", "type"=>"creditcard", "client"=>"client_e4fb7f288afc4912e864", "card_type"=>"visa", "country"=>nil, "expire_month"=>"12", "expire_year"=>"2015", "card_holder"=>"Water Schreppers", "last4"=>"1111", "created_at"=>1377529281, "updated_at"=>1377529283, "app_id"=>nil}, @amount="69900", @is_fraud=false, @refunds=nil, @fees=[], @id="tran_7d1a9c12f4ee737a23bd2fcbb69e", @created_at=2013-08-26 17:01:23 +0200, @currency="EUR">

      @payment_transaction = PaymentTransaction.create( 
                                                :description  => transaction.description ,
                                                #:amount       => transaction.origin_amount,
                                                :client       => transaction.client,
                                                #:client_email => transaction.email,
                                                :payment      => transaction.payment,
                                                :paymill_hash => transaction.to_yaml
                                            )

  
      #logger.info( trans.inspect )

    rescue Paymill::APIError
      @payment_transaction = nil
    end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product]) #investigate strong params here!!!!
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def product_params
      params.require(:product).permit(:description, :name, :price)
    end
end

app/views/products/_details.html.erb
<% @cart = "yes we can!" %>

<p id="notice"><%= notice %></p>
<div class="span8 well">
  <div class="span6">
  <%#= image_tag product.first_picture %>
    <% product.pictures.each do |picture| %>
      <%= link_to image_tag(picture.pic.thumb, :title=>picture.title), picture.pic.url(:large) , "data-blightbox"=>"blightbox", :rel=>"single-gallery-id" %> 
    <% end %>

  </div>
  <div class="span6">
    <p>
      <b>Name:</b>
      <%= product.name %>
    </p>

    <p>
      <b>Price:</b>
      &euro; <%= product.price %>
    </p>

    <p>
      <b>Description:</b>
      <%= product.description.html_safe %>
    </p>
    <%#= link_to "Add to cart", holiday_path, :class=>"btn btn-success pull-right" %>
    <%= link_to "Buy now", buy_product_path(product), :class=>"btn btn-success pull-right" %>
    <%= link_to 'Back', products_path, :class=>"btn" %>
    <% if current_login && current_login.role?("Administrator") %>
      <%= link_to 'Edit', edit_product_path(product), :class=>"btn btn-primary" %> 
    <% end %>

  </div>
</div>


<%= content_for :javascript do %>
  <script language="javascript">
      $(document).ready(function (){
          $("#pikame").PikaChoose();
        });
    </script>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(@product, :html=>{ :class=>"form-horizontal", :multipart=>true } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= render 'pictures', :f=>f %>
   
    <%= f.association :category %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= link_to 'Cancel', products_path, :class=>"btn" %>
    <%= f.button :submit, :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/products/_picture_fields.html.erb
<div class="form-inputs">

    <%= link_to_remove_association icon('remove') + "", f, :class => "btn btn-small btn-danger pull-right", :style => "margin-left: 180px; margin-bottom: 10px;" %>
    <%= f.input :title %>

      <div class="control-group">
      <%= f.label :picture, :class=>'string optional control-label' %>
        <div class="controls">
          <%= image_tag(f.object.pic.thumb, :class=>'picture') if f.object.pic.present? %>
          <%= f.file_field :pic, :class=>'string optional' %>
          <%= f.hidden_field :pic_cache %>
        </div>
      </div>


</div>

app/views/products/_pictures.html.erb
<div class="nested-fields">
 <div id="pictures">
    <%= f.simple_fields_for :pictures do |form| %>
      <%= render 'picture_fields', :f => form %>
    <% end %>
  </div>

  <div class="links">
    <%= link_to_add_association icon('plus') + ' add picture', f, :pictures, :style => "margin-left: 180px;", :class => "btn btn-small" %>
  </div>
  <hr />

</div>

app/views/products/_show.html.erb
       <li class="span2" style="width:210px; margin-left:0px;margin-right: 10px;">
            <div class="thumbnail">
              <%= link_to image_tag(product.thumbnail), product_path(product), :id=>"product_#{product.id}" %>
              <div class="prod_description" style="height:40px;">
                <div class="pull-left" style="width:150px; height:25px;">
                  <b><%= product.name %></b> 
                </div>
                <div class="pull-right"> 
                  &euro; <%= product.price || "Missing price" %> <br/>
                </div>
              </div>

              <div class="clearfix"></div>
              <%= link_to "Details", product, :class=>"btn" %>
              <%#= link_to "Add to cart", holiday_path, :class=>"btn btn-success pull-right" %>
              <%= link_to "Buy", buy_product_path(product), :class=>"btn btn-success pull-right" %>
              </p>
            </div>
            <% if false # if current_login && current_login.role?("Administrator") %>
              <br/> 
              <%= link_to 'Edit', edit_product_path(product), :class=>"btn btn-mini" %>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-mini" %>
            <% end %>
          </li>

app/views/products/buy.html.erb
<%= content_for :javascript do %>

  <script type="text/javascript">
      var PAYMILL_PUBLIC_KEY = '<%= APP_CONFIG[:payment][:public_key] %>';
 
      $(document).ready( function() {
         var translation = new Array();

          //German
          //Creditcard
          translation["de"] = new Object();
          translation["de"]["form"] = new Object();
          translation["de"]["form"]["card-paymentname"] = 'Kreditkarte';
          translation["de"]["form"]["card-number"] = 'Kartennummer';
          translation["de"]["form"]["card-cvc"] = 'CVC';
          translation["de"]["form"]["card-holdername"] = 'Karteninhaber';
          translation["de"]["form"]["card-expiry"] = 'Gültigkeitsdatum (MM/YYYY)';
          translation["de"]["form"]["amount"] = 'Betrag';
          translation["de"]["form"]["currency"] = 'Währung';
          translation["de"]["form"]["submit-button"] = 'Abschicken';
          //Elv
          translation["de"]["form"]["elv-paymentname"] = 'Elektronisches Lastschriftverfahren';
          translation["de"]["form"]["elv-account"] = 'Kontonummer';
          translation["de"]["form"]["elv-holdername"] = 'Kontoinhaber';
          translation["de"]["form"]["elv-bankcode"] = 'Bankleitzahl';
          
          //Error
          translation["de"]["error"] = new Object();
          translation["de"]["error"]["invalid-card-number"] = 'Ungültige Kartennummer';
          translation["de"]["error"]["invalid-card-expiry-date"] = 'Ungültiges Gültigkeitsdatum';
          translation["de"]["error"]["invalid-card-holdername"] = 'Bitte geben Sie den Karteninhaber an.';
          translation["de"]["error"]["invalid-elv-holdername"] = 'Bitte geben Sie den Kontoinhaber an.';
          translation["de"]["error"]["invalid-elv-accountnumber"] = 'Bitte geben Sie eine gültige Kontonummer ein.';
          translation["de"]["error"]["invalid-elv-bankcode"] = 'Bitte geben Sie eine gültige BLZ ein.';
          
          //English
          //Creditcard
          translation["en"] = new Object();
          translation["en"]["form"] = new Object();
          translation["en"]["form"]["card-paymentname"] = 'Credit card';
          translation["en"]["form"]["card-number"] = 'Card number';
          translation["en"]["form"]["card-cvc"] = 'CVC';
          translation["en"]["form"]["card-holdername"] = 'Card holder';
          translation["en"]["form"]["card-expiry"] = 'Valid until (MM/YYYY)';
          translation["en"]["form"]["amount"] = 'Amount';
          translation["en"]["form"]["currency"] = 'Currency';
          translation["en"]["form"]["submit-button"] = 'Submit';
          //Elv
          translation["en"]["form"]["elv-paymentname"] = 'Direct debit';
          translation["en"]["form"]["elv-account"] = 'Account number';
          translation["en"]["form"]["elv-holdername"] = 'Account holder';
          translation["en"]["form"]["elv-bankcode"] = 'Bank code';
          
          //Error
          translation["en"]["error"] = new Object();
          translation["en"]["error"]["invalid-card-number"] = 'Invalid card number.';
          translation["en"]["error"]["invalid-card-expiry-date"] = 'Invalid expire date.';
          translation["en"]["error"]["invalid-card-holdername"] = 'Please enter the card holder name.';
          translation["en"]["error"]["invalid-elv-holdername"] = 'Please enter the account holder name.';
          translation["en"]["error"]["invalid-elv-accountnumber"] = 'Please enter a valid account number.';
          translation["en"]["error"]["invalid-elv-bankcode"] = 'Please enter a valid bank code.';

    });
  </script>

  <script src="https://bridge.paymill.com/"></script>
  <script language="javascript" type="text/javascript">
      $(document).ready(function () {
          function PaymillResponseHandler(error, result) {
              if (error) {
                  // Show the error message above the form
                  $(".payment-errors").text(error.apierror);
              } else {
                  $(".payment-errors").text("");
                  var form = $("#payment-form");
                  // Token
                  var token = result.token;
                  // Insert token into the payment form
                  form.append("<input type='hidden' name='paymillToken' value='" + token + "'/>");

                    //alert("token = "+result.token);
                  form.get(0).submit();
              }
              $(".submit-button").removeAttr("disabled");
          }

          $("#payment-form").submit(function (event) {
              // Deactivate the submit button to avoid further clicks
              $('.submit-button').attr("disabled", "disabled");
              if (false == paymill.validateCardNumber($('.card-number').val())) {
                  $(".payment-errors").text("Invalid card number");
                  $(".submit-button").removeAttr("disabled");
                  return false;
              }

              if (false == paymill.validateExpiry($('.card-expiry-month').val(), $('.card-expiry-year').val())) {
                  $(".payment-errors").text("Invalid date of expiry");
                  $(".submit-button").removeAttr("disabled");
                  return false;
              }

              paymenttype = $('.paymenttype.disabled').length ? $('.paymenttype.disabled').val() : 'cc';
              switch (paymenttype) {
                  case "cc":
                      var params = {
                          amount_int:     $('.card-amount-int').val(),  // E.g. "15" for 0.15 Eur
                          //amount:         $('.card-amount').val(),    // deprecated!
                          currency:       $('.card-currency').val(),    // ISO 4217 e.g. "EUR"
                          number:         $('.card-number').val(),
                          exp_month:      $('.card-expiry-month').val(),
                          exp_year:       $('.card-expiry-year').val(),
                          cvc:            $('.card-cvc').val(),
                          cardholder:     $('.card-holdername').val()
                      };
                      break;

                  case "elv":
                      var params = {
                          number:         $('.elv-account').val(),
                          bank:           $('.elv-bankcode').val(),
                          accountholder:  $('.elv-holdername').val()
                      };
                      break;
              }
              paymill.createToken(params, PaymillResponseHandler);

              return false;
          });

          // Toggle buttons and forms
          $(".paymenttype").click(function (event) {
              $(this).addClass('btn-primary disabled');
              $('#payment-form-cc').toggle();
              //$('#payment-form-elv').toggle();
              if($(this).val()=='cc') {
                  $('#btn-paymenttype-elv').removeClass('btn-primary disabled');
              }
              else {
                  $('#btn-paymenttype-cc').removeClass('btn-primary disabled');                  
              }
          });
          

      });
  </script>

<% end %>


<div class="controls controls-row">
<p>
Webshop is currently down. I'm fully occupied as a new Dad and together with a full time contracting job at
<a href="http://rombit.be" target="_blank">ROMBIT</a> this is taking up all my time.
</p>

<br/>
<%= image_tag "noah_1_maand.png" %>

<p>
Shop will become active once I find some spare time.
Meanwhile there's a couple of kits in stock. <br/>
E-mail me at <a href="mailto:walter@sitweb.eu">walter@sitweb.eu</a> if you're interested.
Prices are with a big discount for these last few remaining kits ...
</p>

<br/><br/>
Kind regards, <br/>
Walter

<br/>

</div>



<!--
div class="controls controls-row">
  <div class="btn-group span4">
  <button id="btn-paymenttype-cc" class="paymenttype btn btn-primary disabled" value="cc">VISA & Mastercard</button>
   button id="btn-paymenttype-elv" class="paymenttype btn" value="elv">ELV</button>
  </div>
</div>

<br/>

<form id="payment-form" class="form span8" action="<%= pay_product_path( @product ) %>" method="POST">
 <p class="payment-errors alert-error span3" style="display:none;"></p>
 <div id="payment-form-cc">
  <div class="controls controls-row">
   <div class="span4">
    <label class="card-number-label">Credit Card</label>
    <input class="card-number span8" type="text" size="20" value="4111111111111111"/>
   </div>
   <div class="span4">
    <label class="card-cvc-label">CVC</label>
    <input class="card-cvc span3" type="text" size="4" value="111"/>
   </div>
  </div>
  <div class="controls controls-row">
   <div class="span3 card-icon"></div>
  </div>
  <div class="controls controls-row">
   <div class="span3">
    <label class="card-holdername-label">Card owner</label>
    <input class="card-holdername span12" type="text" size="20" value=""/>
   </div>
  </div>
  <div class="controls controls-row">
   <div class="span3">
    <label class="card-expiry-label">Expiry date (MM/YYYY)</label>
    <input class="card-expiry-month span3" type="text" size="2" value="12"/>

    <span style="float:left;"> / </span> &nbsp;

    <input class="card-expiry-year span4" type="text" size="4" value="2015"/>
   </div>
  </div>
 </div>
 <div id="payment-form-elv" style="display: none;">
  <div class="controls controls-row">
   <div class="span3">
    <label class="elv-holdername-label">Card holder</label>
    <input class="elv-holdername span3" type="text" size="20" value=""/>
   </div>
  </div>
  <div class="controlscontrols-row">
   <div class="span3">
    <label class="elv-account-label">Kontonummer</label>
    <input class="elv-account span3" type="text" size="20" value="1234567890"/>
   </div>
  </div>
  <div class="controls controls-row">
   <div class="span3">
    <label class="elv-bankcode-label">Bankleitzahl</label>
    <input class="elv-bankcode span3" type="text" size="20" value="99999999"/>
   </div>
  </div>
 </div>


 <div class="controls controls-row">
   <div class="span4"><label class="amount-label">Amount</label>
    &euro; <%= @product.price %>
    <br/>
    <input class="hidden amount span6" type="text" size="5" value="<%= @product.price %>" name="amount"/>
    
   </div>
   --div class="span4"><label class="currency-label">Currency</label>
    <input class="hidden currency span2" type="text" size="3" value="EUR" name="currency"/>
  </div>
  <div class="controls controls-row">
   <div class="span4">
    <button class="submit-button btn btn-primary" type="submit"> Buy now </button>
   </div>
  </div>
 </form>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%#= link_to 'Show', @product %> 

app/views/products/index.html.erb
    
    
<% @cart = "yes we can!" %>
    <% if false #current_login && current_login.role?("Administrator") %>
      <%= link_to 'New Product', new_product_path, :class=>"btn btn-primary" %> <br/><br/>
    <% end %>
 
    <% if @products.count > 0 %>
      <ul class="thumbnails">
        <% @products.each do |product| %>
          <%= render 'show', :product=>product %>
        <% end %>
      </ul>
    <% end %>
   

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/pay.html.erb
<div class="well">

<% if @payment_transaction.present? %>
  <p>
    Thank you for your purchase. <br/>
    Your transaction ID is # <%= @payment_transaction.id %>
  </p>
  <p>
    We will inform you per e-mail as soon as your purchase has been shipped.
  </p>

<% else %>
  Error: your payment could not be processed or you pressed refresh on this page.
<% end %>

</div>

app/views/products/show.html.erb
<%= render 'details', :product => @product %>